### ISSUE TITLE
LocalSettings.php and extensions are not loading

### ISSUE THREAD

**Issue by nischayn22** [CanastaWiki/Canasta-DockerCompose#10]
The LocalSettings.php file isn't linked/mounted as required.
The extensions are mounted as user-extensions and that is resulting in the following error:

<b>Fatal error</b>:  Uncaught Exception: Unable to open file /var/www/mediawiki/w/extensions/ExtensionName/extension.json: filemtime(): stat failed for /var/www/mediawiki/w/extensions/ExtensionName/extension.json in /var/www/mediawiki/w/includes/registration/ExtensionRegistry.php:177
Stack trace:
#0 /var/www/mediawiki/w/includes/GlobalFunctions.php(51): ExtensionRegistry-&gt;queue()
#1 /mediawiki/config/LocalSettings.php(434): wfLoadExtension()
#2 /var/www/mediawiki/w/includes/Setup.php(143): require_once('/mediawiki/conf...')
#3 /var/www/mediawiki/w/includes/WebStart.php(89): require_once('/var/www/mediaw...')
#4 /var/www/mediawiki/w/index.php(44): require('/var/www/mediaw...')
#5 {main}
  thrown in <b>/var/www/mediawiki/w/includes/registration/ExtensionRegistry.php</b> on line <b>177</b><br />
* Connection #0 to host localhost left intact

**Comment by jeffw16** [comment]
Are you using the latest version of Canasta? Versions of Canasta released before April 7 are considered pre-GA and are not officially supported.

**Comment by nischayn22** [comment]
I didn't specify a version. So I guess whatever comes by default with this
docker compose.
